[package]
name = "aquarium"
version = "0.1.0"
authors = ["Nathan Stocks <nathan@agileperception.com>"]
edition = "2018"

[dependencies]
# I thought you might want this for your library...
thiserror = "1.0"
# ...and this for your binary
anyhow = "1.0"
